# GLOBAL SETTINGS
cname: hallpayne.yourwebvisual.com
allow_robots: false

# META
title: Hall Payne
title_homepage: Personal Injury & Employment Law Specialists | Hall Payne
company: Hall Payne Lawyers
description:

# DEVELOPER
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/hallpa-0119
github_repo_name: hallpa-0119
jekyll_version: 3.7.0

# OFFICES
offices:
  - title: Australia
    address:
    phone: 1800 659 114
    email: general@hallpayne.com.au
    po_box: Locked bag 2013<br> South Brisbane 4101

# GOOGLE
google_analytics: #UA-XXXXXXXX-X

# AUTHOR
author:
  title: Much Media
  url: http://www.muchmedia.com.au
  logo: /assets/img/ui/much-media-logo.svg
  description: Website by Much Media